import type { EmbedBuilder } from 'discord.js';
import { Prisma, defaultRetentionPolicy } from '@pavisie/database';
import type { LogKind, LogPayload, LoggingService, PluginContext } from '../sdk';
import { LogBatcher } from './batcher';
import { LOG_KIND_LABELS } from './constants';
import { buildLogEmbed } from './embed-builder';
import { resolveLogChannelId } from './channel-resolution';
import { redactText } from './redaction';
import { pruneUndefined } from './util';
import type { LoggingConfig } from './manifest';

const PLUGIN_ID = 'logging' as const;

function redactPayload(payload: LogPayload, customPatterns: string[], allowContent: boolean): LogPayload {
  const redacted: LogPayload = {
    ...payload,
    description:
      payload.description !== undefined ? redactText(payload.description, customPatterns) : undefined,
    fields: payload.fields?.map((field) => ({ ...field, value: redactText(field.value, customPatterns) })),
    contentBefore:
      allowContent && payload.contentBefore !== undefined
        ? redactText(payload.contentBefore, customPatterns)
        : undefined,
    contentAfter:
      allowContent && payload.contentAfter !== undefined
        ? redactText(payload.contentAfter, customPatterns)
        : undefined,
    attachments: allowContent && payload.attachments ? payload.attachments : undefined,
  };
  return pruneUndefined(redacted as unknown as Record<string, unknown>) as unknown as LogPayload;
}

/** Sample payload used by `/logs test` and the dashboard's redaction/test tooling to show what a real log embed looks like. */
export function buildSamplePayload(kind: LogKind, requestedBy: string): LogPayload {
  return {
    actorId: requestedBy,
    title: `${LOG_KIND_LABELS[kind]} (test)`,
    description: `This is a sample **${kind}** log entry generated by \`/logs test\`. It exercises the same code path as a real event — routing, redaction, batching, and storage all behave exactly the way they would for the real thing.`,
    fields: [{ name: 'Sample field', value: 'sample-value@example.com (this line demonstrates redaction)' }],
  };
}

/**
 * Implements `ServiceMap['logging']` (ARCHITECTURE.md §7.5): resolves the configured channel for a `LogKind`,
 * redacts sensitive text, builds a compact embed, queues it into a per-channel `LogBatcher` (flush every 2s or
 * 5 embeds), and — unless the guild turned it off — stores a `LogEvent` row. Every other plugin/event handler
 * in this file goes through `log()`; nothing else touches the batcher or the `LogEvent` table directly.
 */
export class LoggingServiceImpl implements LoggingService {
  private readonly batcher: LogBatcher;

  constructor(private readonly ctx: PluginContext) {
    this.batcher = new LogBatcher({
      send: (channelId, embeds) => this.sendBatch(channelId, embeds),
      onError: (channelId, err) => {
        const message = err instanceof Error ? err.message : String(err);
        this.ctx.logger.error({ channelId, err: message }, 'logging: failed to flush a batch of log embeds');
      },
    });
  }

  private async sendBatch(channelId: string, embeds: EmbedBuilder[]): Promise<void> {
    const channel = await this.ctx.client.channels.fetch(channelId).catch(() => null);
    if (!channel || !channel.isTextBased() || channel.isDMBased()) return;
    await channel.send({ embeds, allowedMentions: { parse: [] } });
  }

  async log(guildId: string, kind: LogKind, payload: LogPayload): Promise<void> {
    const config = await this.ctx.getConfig<LoggingConfig>(guildId);
    if (!config.enabledKinds.includes(kind)) return;

    const host = this.ctx.services.get('host');
    const guildConfig = host ? await host.getGuildConfig(guildId) : null;
    const allowContent = Boolean(guildConfig?.logMessageContent) && config.captureContent;

    const redacted = redactPayload(payload, config.redactionPatterns, allowContent);

    const channelId = resolveLogChannelId(config.channels, kind);
    if (channelId) {
      const embed = buildLogEmbed({ kind, guildId, payload: redacted });
      this.batcher.enqueue(channelId, embed);
    }

    if (config.storeEvents) {
      try {
        await this.ctx.prisma.logEvent.create({
          data: {
            guildId,
            kind,
            actorId: redacted.actorId ?? null,
            targetId: redacted.targetId ?? null,
            channelId: redacted.channelId ?? null,
            messageId: redacted.messageId ?? null,
            payload: pruneUndefined(redacted as unknown as Record<string, unknown>) as Prisma.InputJsonValue,
          },
        });
      } catch (err) {
        this.ctx.logger.error(
          { guildId, kind, err: err instanceof Error ? err.message : String(err) },
          'logging: failed to store a LogEvent row',
        );
      }
    }
  }

  /** Sends a sample log through the exact same pipeline as a real event (`/logs test`). */
  async sendTest(guildId: string, kind: LogKind, requestedBy: string): Promise<void> {
    await this.log(guildId, kind, buildSamplePayload(kind, requestedBy));
  }

  /**
   * Deletes `LogEvent` rows for `guildId` older than `min(config.retentionDays, DataRetentionPolicy.logEventDays)`
   * days (ARCHITECTURE.md's logging task retention rule). Used by both the `logging:retention` repeat job and
   * (indirectly, via the shared `runRetentionForGuild`) the platform-wide `DataRetentionPolicy` sweep — running
   * both is harmless (the second sweep just deletes zero additional rows) and keeps this plugin's own,
   * more-specific `retentionDays` setting enforced even between platform-wide sweeps.
   */
  async purgeRetention(guildId: string): Promise<number> {
    const config = await this.ctx.getConfig<LoggingConfig>(guildId);
    const policy = await this.ctx.prisma.dataRetentionPolicy.findUnique({ where: { guildId } });
    const policyDays = policy?.logEventDays ?? defaultRetentionPolicy.logEventDays;
    const effectiveDays = Math.min(config.retentionDays, policyDays);

    const cutoff = new Date(Date.now() - effectiveDays * 24 * 60 * 60 * 1000);
    const result = await this.ctx.prisma.logEvent.deleteMany({
      where: { guildId, createdAt: { lt: cutoff } },
    });
    return result.count;
  }

  /** Flushes every channel's pending batch immediately (best-effort, used on plugin/process shutdown). */
  flushAll(): void {
    this.batcher.flushAll();
  }
}

export { PLUGIN_ID as LOGGING_PLUGIN_ID };

// `ServiceMap['logging']` (the SDK's cross-plugin service contract) only declares `log()` — `sendTest` and
// `purgeRetention` are this plugin's own extras, used by its own commands/jobs. Rather than casting through the
// generic `ServiceRegistry` to reach them, `onLoad` stashes the concrete instance here so same-plugin code
// (commands/logs.ts, jobs/retention.ts) can call them with full typing; other plugins only ever see `log()`
// via `ctx.services.get('logging')`, which is the intended, narrower cross-plugin surface.
let instance: LoggingServiceImpl | null = null;

export function setLoggingServiceInstance(impl: LoggingServiceImpl): void {
  instance = impl;
}

export function getLoggingServiceInstance(): LoggingServiceImpl | null {
  return instance;
}
